SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/local/lib/")
SEARCH_DIR("./powerpc64/")
SEARCH_DIR("./systems/")
SEARCH_DIR("/root/Downloads/fpc-3.2.0-devel/rtl/units/powerpc64-freebsd/")
SEARCH_DIR("./ppcgen/")
INPUT(
/root/Downloads/fpc-3.2.0-devel/rtl/units/powerpc64-freebsd/prt0.o
powerpc64/units/powerpc64-freebsd/pp.o
system.o
objpas.o
powerpc64/units/powerpc64-freebsd/catch.o
powerpc64/units/powerpc64-freebsd/globals.o
powerpc64/units/powerpc64-freebsd/compiler.o
baseunix.o
unix.o
powerpc64/units/powerpc64-freebsd/verbose.o
unixtype.o
sysctl.o
syscall.o
unixutil.o
sysutils.o
powerpc64/units/powerpc64-freebsd/cutils.o
powerpc64/units/powerpc64-freebsd/globtype.o
powerpc64/units/powerpc64-freebsd/finput.o
powerpc64/units/powerpc64-freebsd/cmsgs.o
freebsd.o
errors.o
sysconst.o
powerpc64/units/powerpc64-freebsd/constexp.o
powerpc64/units/powerpc64-freebsd/cclasses.o
powerpc64/units/powerpc64-freebsd/cstreams.o
powerpc64/units/powerpc64-freebsd/comphook.o
powerpc64/units/powerpc64-freebsd/cfileutl.o
powerpc64/units/powerpc64-freebsd/systems.o
powerpc64/units/powerpc64-freebsd/cpuinfo.o
powerpc64/units/powerpc64-freebsd/version.o
powerpc64/units/powerpc64-freebsd/fmodule.o
powerpc64/units/powerpc64-freebsd/switches.o
powerpc64/units/powerpc64-freebsd/ogbase.o
powerpc64/units/powerpc64-freebsd/fpkg.o
powerpc64/units/powerpc64-freebsd/symbase.o
powerpc64/units/powerpc64-freebsd/symsym.o
powerpc64/units/powerpc64-freebsd/wpobase.o
powerpc64/units/powerpc64-freebsd/aasmbase.o
powerpc64/units/powerpc64-freebsd/aasmdata.o
powerpc64/units/powerpc64-freebsd/owbase.o
powerpc64/units/powerpc64-freebsd/ogmap.o
powerpc64/units/powerpc64-freebsd/symconst.o
powerpc64/units/powerpc64-freebsd/compinnr.o
powerpc64/units/powerpc64-freebsd/widestr.o
powerpc64/units/powerpc64-freebsd/symtype.o
powerpc64/units/powerpc64-freebsd/symdef.o
powerpc64/units/powerpc64-freebsd/defcmp.o
powerpc64/units/powerpc64-freebsd/cgbase.o
powerpc64/units/powerpc64-freebsd/cgutils.o
powerpc64/units/powerpc64-freebsd/parabase.o
charset.o
cp1251.o
cp866.o
cp8859_5.o
cp1253.o
cp8859_1.o
cp850.o
cp437.o
cp1252.o
cp646.o
cp874.o
cp856.o
cp852.o
cp8859_2.o
cp1250.o
cp1254.o
cp1255.o
cp1256.o
cp1257.o
cp1258.o
powerpc64/units/powerpc64-freebsd/ppu.o
powerpc64/units/powerpc64-freebsd/entfile.o
powerpc64/units/powerpc64-freebsd/fpccrc.o
powerpc64/units/powerpc64-freebsd/crefs.o
powerpc64/units/powerpc64-freebsd/tokens.o
powerpc64/units/powerpc64-freebsd/node.o
powerpc64/units/powerpc64-freebsd/aasmtai.o
powerpc64/units/powerpc64-freebsd/optbase.o
powerpc64/units/powerpc64-freebsd/cpubase.o
strings.o
powerpc64/units/powerpc64-freebsd/rgbase.o
powerpc64/units/powerpc64-freebsd/itcpugas.o
powerpc64/units/powerpc64-freebsd/cgobj.o
powerpc64/units/powerpc64-freebsd/aasmcpu.o
powerpc64/units/powerpc64-freebsd/rgobj.o
powerpc64/units/powerpc64-freebsd/nutils.o
powerpc64/units/powerpc64-freebsd/nflw.o
powerpc64/units/powerpc64-freebsd/defutil.o
powerpc64/units/powerpc64-freebsd/symtable.o
powerpc64/units/powerpc64-freebsd/paramgr.o
powerpc64/units/powerpc64-freebsd/objcdef.o
powerpc64/units/powerpc64-freebsd/pgenutil.o
powerpc64/units/powerpc64-freebsd/gendef.o
powerpc64/units/powerpc64-freebsd/symcpu.o
powerpc64/units/powerpc64-freebsd/symutil.o
powerpc64/units/powerpc64-freebsd/procinfo.o
powerpc64/units/powerpc64-freebsd/scanner.o
powerpc64/units/powerpc64-freebsd/tgobj.o
powerpc64/units/powerpc64-freebsd/hlcgobj.o
powerpc64/units/powerpc64-freebsd/aasmsym.o
powerpc64/units/powerpc64-freebsd/procdefutil.o
powerpc64/units/powerpc64-freebsd/pparautl.o
powerpc64/units/powerpc64-freebsd/blockutl.o
powerpc64/units/powerpc64-freebsd/nbas.o
powerpc64/units/powerpc64-freebsd/dbgbase.o
powerpc64/units/powerpc64-freebsd/fppu.o
powerpc64/units/powerpc64-freebsd/dirparse.o
powerpc64/units/powerpc64-freebsd/options.o
powerpc64/units/powerpc64-freebsd/wpoinfo.o
powerpc64/units/powerpc64-freebsd/parser.o
powerpc64/units/powerpc64-freebsd/fpcp.o
powerpc64/units/powerpc64-freebsd/comprsrc.o
powerpc64/units/powerpc64-freebsd/cscript.o
powerpc64/units/powerpc64-freebsd/rabase.o
powerpc64/units/powerpc64-freebsd/pkgutil.o
powerpc64/units/powerpc64-freebsd/i_bsd.o
powerpc64/units/powerpc64-freebsd/link.o
powerpc64/units/powerpc64-freebsd/ldscript.o
powerpc64/units/powerpc64-freebsd/aasmcnst.o
powerpc64/units/powerpc64-freebsd/psub.o
powerpc64/units/powerpc64-freebsd/pdecsub.o
powerpc64/units/powerpc64-freebsd/export.o
powerpc64/units/powerpc64-freebsd/optdfa.o
powerpc64/units/powerpc64-freebsd/pass_1.o
powerpc64/units/powerpc64-freebsd/nld.o
powerpc64/units/powerpc64-freebsd/ncon.o
powerpc64/units/powerpc64-freebsd/ncnv.o
powerpc64/units/powerpc64-freebsd/nset.o
powerpc64/units/powerpc64-freebsd/ncal.o
powerpc64/units/powerpc64-freebsd/nadd.o
powerpc64/units/powerpc64-freebsd/nmem.o
powerpc64/units/powerpc64-freebsd/ninl.o
powerpc64/units/powerpc64-freebsd/htypechk.o
powerpc64/units/powerpc64-freebsd/pgentype.o
powerpc64/units/powerpc64-freebsd/nmat.o
powerpc64/units/powerpc64-freebsd/nobjc.o
powerpc64/units/powerpc64-freebsd/ngenutil.o
powerpc64/units/powerpc64-freebsd/objcutil.o
powerpc64/units/powerpc64-freebsd/optloop.o
powerpc64/units/powerpc64-freebsd/ncgmem.o
powerpc64/units/powerpc64-freebsd/optutils.o
powerpc64/units/powerpc64-freebsd/nopt.o
powerpc64/units/powerpc64-freebsd/pass_2.o
powerpc64/units/powerpc64-freebsd/objcgutl.o
powerpc64/units/powerpc64-freebsd/ncgrtti.o
powerpc64/units/powerpc64-freebsd/ncgutil.o
powerpc64/units/powerpc64-freebsd/hlcgcpu.o
powerpc64/units/powerpc64-freebsd/cpupi.o
powerpc64/units/powerpc64-freebsd/hlcgppc.o
powerpc64/units/powerpc64-freebsd/hlcg2ll.o
powerpc64/units/powerpc64-freebsd/cgppc.o
powerpc64/units/powerpc64-freebsd/symcreat.o
powerpc64/units/powerpc64-freebsd/pbase.o
powerpc64/units/powerpc64-freebsd/pstatmnt.o
powerpc64/units/powerpc64-freebsd/pdecl.o
powerpc64/units/powerpc64-freebsd/pexports.o
powerpc64/units/powerpc64-freebsd/opttail.o
powerpc64/units/powerpc64-freebsd/optcse.o
powerpc64/units/powerpc64-freebsd/optconstprop.o
powerpc64/units/powerpc64-freebsd/optdeadstore.o
powerpc64/units/powerpc64-freebsd/optloadmodifystore.o
powerpc64/units/powerpc64-freebsd/aopt.o
powerpc64/units/powerpc64-freebsd/pdecobj.o
powerpc64/units/powerpc64-freebsd/ptconst.o
powerpc64/units/powerpc64-freebsd/pexpr.o
powerpc64/units/powerpc64-freebsd/pdecvar.o
powerpc64/units/powerpc64-freebsd/ptype.o
powerpc64/units/powerpc64-freebsd/pinline.o
powerpc64/units/powerpc64-freebsd/cpupara.o
powerpc64/units/powerpc64-freebsd/syscinfo.o
powerpc64/units/powerpc64-freebsd/nobj.o
powerpc64/units/powerpc64-freebsd/ngtcon.o
powerpc64/units/powerpc64-freebsd/cgcpu.o
powerpc64/units/powerpc64-freebsd/rgcpu.o
powerpc64/units/powerpc64-freebsd/aasmdef.o
powerpc64/units/powerpc64-freebsd/aoptobj.o
powerpc64/units/powerpc64-freebsd/aoptbase.o
powerpc64/units/powerpc64-freebsd/aoptcpub.o
powerpc64/units/powerpc64-freebsd/aoptda.o
powerpc64/units/powerpc64-freebsd/aoptutils.o
powerpc64/units/powerpc64-freebsd/aoptcpu.o
powerpc64/units/powerpc64-freebsd/pcp.o
powerpc64/units/powerpc64-freebsd/globstat.o
powerpc64/units/powerpc64-freebsd/scandir.o
powerpc64/units/powerpc64-freebsd/psystem.o
powerpc64/units/powerpc64-freebsd/pmodules.o
powerpc64/units/powerpc64-freebsd/assemble.o
powerpc64/units/powerpc64-freebsd/import.o
powerpc64/units/powerpc64-freebsd/cresstr.o
powerpc64/units/powerpc64-freebsd/ncgvmt.o
unixcp.o
fpwidestring.o
math.o
powerpc64/units/powerpc64-freebsd/wpo.o
powerpc64/units/powerpc64-freebsd/cpunode.o
powerpc64/units/powerpc64-freebsd/cputarg.o
unicodedata.o
unicodenumtable.o
powerpc64/units/powerpc64-freebsd/optvirt.o
powerpc64/units/powerpc64-freebsd/optdead.o
powerpc64/units/powerpc64-freebsd/ncgbas.o
powerpc64/units/powerpc64-freebsd/ncgld.o
powerpc64/units/powerpc64-freebsd/ncgflw.o
powerpc64/units/powerpc64-freebsd/ncgcnv.o
powerpc64/units/powerpc64-freebsd/ncgcon.o
powerpc64/units/powerpc64-freebsd/ncgcal.o
powerpc64/units/powerpc64-freebsd/ncgset.o
powerpc64/units/powerpc64-freebsd/ncginl.o
powerpc64/units/powerpc64-freebsd/ncgopt.o
powerpc64/units/powerpc64-freebsd/ncgobjc.o
powerpc64/units/powerpc64-freebsd/nppcadd.o
powerpc64/units/powerpc64-freebsd/nppccal.o
powerpc64/units/powerpc64-freebsd/ngppcset.o
powerpc64/units/powerpc64-freebsd/ngppcinl.o
powerpc64/units/powerpc64-freebsd/nppcmat.o
powerpc64/units/powerpc64-freebsd/nppccnv.o
powerpc64/units/powerpc64-freebsd/nppcld.o
powerpc64/units/powerpc64-freebsd/ncgadd.o
powerpc64/units/powerpc64-freebsd/ngppcadd.o
powerpc64/units/powerpc64-freebsd/ncgmat.o
powerpc64/units/powerpc64-freebsd/ngppccnv.o
powerpc64/units/powerpc64-freebsd/t_linux.o
powerpc64/units/powerpc64-freebsd/t_bsd.o
powerpc64/units/powerpc64-freebsd/t_aix.o
powerpc64/units/powerpc64-freebsd/agppcgas.o
powerpc64/units/powerpc64-freebsd/rappcgas.o
powerpc64/units/powerpc64-freebsd/dbgstabx.o
powerpc64/units/powerpc64-freebsd/dbgdwarf.o
powerpc64/units/powerpc64-freebsd/expunix.o
powerpc64/units/powerpc64-freebsd/ogelf.o
powerpc64/units/powerpc64-freebsd/owar.o
powerpc64/units/powerpc64-freebsd/rescmn.o
powerpc64/units/powerpc64-freebsd/i_linux.o
powerpc64/units/powerpc64-freebsd/elfbase.o
powerpc64/units/powerpc64-freebsd/i_aix.o
powerpc64/units/powerpc64-freebsd/aggas.o
powerpc64/units/powerpc64-freebsd/objcasm.o
powerpc64/units/powerpc64-freebsd/raatt.o
powerpc64/units/powerpc64-freebsd/rappc.o
powerpc64/units/powerpc64-freebsd/rasm.o
powerpc64/units/powerpc64-freebsd/rautils.o
powerpc64/units/powerpc64-freebsd/dbgstabs.o
)
